import * as React from 'react'
import Layout from '../components/layout'
const AboutPage = () => {
  return (
    <Layout pageTitle="Den harmoniska kroppen">

<h3>Att andas</h3> 
<p>Andningen omspänner och mäter exakt ut hela vår livslängd, från det första skriket till det sista andetaget. Det är redo att fungera från det vi föds. Det är inte vår egen ansträngning och livserfarenhet som gör att  vi kan lita på den, utan det är den djupt liggande vishet som handlar i vårt omedvetna redan under fosterstadiet. Vid födelsen har hjärtat redan slagit sedan länge, och andningen anpassar undan för undan sin rytm till pulsen till dess den stabiliseras omkring förhållandet ett andetag på fyra hjärtslag. Andningens och hjärtverksamhetens regleringscentra ligger intill varandra i förlängda märgen, hjärnans allra djupaste och mest omedvetna skikt.</p>
<p>Vi behöver aldrig lära oss att andas. Den kunskap som reglerar andningen ligger före all medveten inlärning. Vi kan andas redan när vi föds, precis som vårt hjärta kan slå redan när vi föds. Vårt första skriḱ satte igång en dittills oanvänd men redan helt arbetsduglig funktion, som långsamt förfinas och anpassar sig för att följa varje etapp av människokroppens växande.</p>
<p>Andningens kemiska funktion är välbekant: att genom gasutbyte tillföra friskt syre till blodet och transportera bort koldioxid. Men andningens rytmiska funktilon är minst lika viktig. Medan hjärtat bestämmer rytmen för blodets cirkulation och därigenom den omedvetna ämnesomsättningen, står andningen i samklang med rytmen i våra handlingar, våra yttre rörelser. På det fysiska planet anpassar den sig till även de finaste nyanser i vår aktivitet.</p>
<h3>Andning och känslor</h3>
<p>På det psykiska planet är det i synnerhet det ständigt fluktuerande känslolivet som kommer till uttryck genom andningen: den blir hämmad när vi är rädda, mer intensiv när vi är arga, snabbare när vi åtrår och långsammare när vi är lugna. Utanför all systematisering och klassificering anpassar andningen sig smidigt till de ständiga förändringarna i vårt inre och yttre liv.</p>
<p>Vissa fysiska faktorer kan påverka andningssystemet direkt via inandningsluften: kyla, värme, fuktighet, luftföroreningar. Men det är förmodligen de emotionella påverkningarna som framför allt orsakar problem med andningen. Andningen visar sig vara känslornas omedelbara uttryck. Denna typ av störningar får oerhörda konsekvenser, som dessutom kan bli mycket långvariga eftersom de grundläggs redan under barndomen. Dessa frön, som psykoanalysen studerar på det psykologiska planet, kommer också att bära frukt på det fysiska planet i vuxen ålder och framför allt påverka andningen.</p>
<p>Det viktiga här är inte känslorna i sig utan om de accepteras eller förkastas av medvetandet. En känsla som accepteras helt och hållet kan liknas vid en eld, som fullständigt bränner upp allt stoff utan att lämna någon aska. När den emotionella vägen förklingat återtar det fysiska livet sitt lugn, precis som havet när vinden mojnat. Men om känslan förnekas och man i stället för "ja" svarar "nej" till den, även om bara till en del, så bildas det avfall, icke förbrända rester. Återgången till den inre friden och friheten blir inte fullständig, utan en lätt spänning finns kvar. Till en början är den alltför svag för att förnimmas, i synnerhet om det är fråga om ett barns ännu odifferentierade medvetnade.</p>
<p>Om dessa känslomässiga avståndstaganden upprepas får de en kumulativ effekt som leder till en muskulär sammandragning. Denna kommer i sin tur att påverka framför allt koordinationen av andningsrörelserna genom spänningar i halsen, bröstkorgen och buken. Andningen tvingas att hålla sig inom allt snävare gränser i en "bur" av låsta spänningar.</p>
<p>Det är mycket viktigt att klart skilja mellan känslan i sig, hur den uttrycks i beteende och övergår till handling.</p> 
<p>Känslan är en inre upplevelse som i sin tur kan leda till vissa yttre handlingar att fly från det som skrämmer oss, att förgöra det som framkallar vår vrede, att bemäktiga sig det vi längtar efter, ja till och med att beröva sig livet i förtvivlan.</p>
<p>Denna förbindelse mellan känsla och handling hindrar dock inte att det rör sig om två helt olika realiteter. Att hejda en destruktiv handling är en helt annan företeelse än att vägra att gå in i den inre känslomässiga upplevelsen: glädjen eller smärtan, fruktan eller vreden, längtan eller hatet. Kroppsligt sett står känslorna i förbindelse med de rytmiska funktionerna, hjärtslag och andning. Handlingen däremot uttrycks via det muskulära systemet och är förbunden med lemmarna.</p>
<p>Det är fullt möjligt att uppleva en ren känsla, liksom en våg som stiger, rullar våldsamt och så planar ut i vårt emotionella liv, utan att det leder till handlingar med katastrofala följder för oss själva eller för vår omgivning.</p>
<h3>Andningen vår inre terapeut</h3>
<p>Å ena sidan undergår andningen förändringar som orsakas av den motoriska aktiviteten och känslorna. Å andra sidan reglerar den själv rytmiskt alla yttre störningar. Liksom pendeln i ett ur strävar den hela tiden tillbaka till en regelbunden rytm. Den försöker absorbera alla yttre förändringar för att integrera dem i en stabil helhet. På så sätt spelar andningen en  terapeutisk roll av första rang.</p>
<p>En övning som utförs regelbundet kan hjälpa oss att dra största möjliga nytta av denna andningens naturliga roll. Andningsreflexerna kan bli våra bundsförvanter i försöken att upplösa konflikterna och gradvis också den bur av muskelspänningar som byggts upp av våra ackumulerade bortträngningar.</p>
<h3>Den centrala övningen</h3>
<p>För att undvika dom yttre hindren så mycket som möjligt skall vi i denna första övning gå tillbaka till den horisontella ställningen från vårt livs första början.</p>
<p><i>Lägg dig på rygg på golvet. Placera en kudde under huvudet så att det kommer upp några centimeter. Kuddens tjocklek kan variera från person till person. Det viktiga är att huvudet får stöd under bakhuvudet, så att halsen lämnas fri och huvudet varken faller bakåt av sin egen tyngd eller pressas framåt; med andra ord; det skall vara bekvämt.</i></p>
<p><i>Sträck ut benen utan att pressa dem mot varandra och låt fötterna falla utåt av sin egen tyngd. Om du i detta läge känner en sträckning i nedre delen av ryggen eller i buken, lägg då en kudde under knäna så att de lyfts upp några centimeter, och låt dem vila på kudden. Det räcker för att spänna av ländmusklerna, som förbinder låren med ryggraden. Spända ländmuskler kan nämligen medföra en känsla av stramning i hela ryggraden.</i></p>
<p><i>När knäna fått den rätta höjden över golvet känns det bekvämt för hela den nedre delen av kroppen.</i></p>
<p><i>Lossa på alla kläder så att ingenting sitter åt mot buken, bröstet eller halsen.</i></p>
<p><i>Lägg händerna på magen med handflatorna öppna och vända nedåt i trakten av solarplexus, dvs i maggropen mitt emellan naveln och spetsen av bröstbenet (benet mitt på bröstkorgens framsida). Låt armbågarna vila på golvet på ömse sidor av kroppen. I denna ställning kan armarna vila utan spänning med fingertopparna i kontakt med buken.</i></p>
<p><i>Håll munnen stängd och andas gemom näsan. Blunda, nu är du klar att börja.</i></p>
<h3>Frihet</h3>
<p><i>Var först uppmärksam på vad som sker under dina fingrar utan att påverka eller förändra någonting, vad det än må vara. Behåll bara kontakten, enkelt och naturligt, med området kring solarplexus.</i></p>
<p><i>Det är mycket möjligt att du till en början inte känner någoting särskilt, att allt verkar helt orörligt. Kanske har du ansträngt dig lite för mycket att vara uppmärksam och därigenom hejdat andningen? Om du märker det, försök då att helt enkelt lämna andningen fri att komma och gå precis som den vill. Se bara till att du inte blockerar den. Ge den tid att hitta sin plats och rytm.</i></p>
<p><i>Du kommer då att känna hur buken rör sig under dina fingrar, till en början nästan omärkligt. Denna rörelse är andningsrytmen som speglas på kroppens yta.</i></p> 
<p><i>Det är mycket viktigt att lämna andningen helt fri att själv söka sig fram till sin egen plats och rytm. Precis som den är, långsam eller snabb, regelbunden eller oregelbunden, är den riktig och rätt. Nöj dig med att lätt och naturligt iaktta hur den kommer och går, utan att ändra någonting.</i></p>
<p><i>Det kan hända att andningen avbryts av suckar eller gäspningar. Suckar och gäspningar är reflexstyrda mekanismer för att reglera andningen, och vi släpper fram, dem utan att hålla emot. Vi får till och med njuta av dem, helt och fullt, när de kommer. Eftersom de svarar mot organismens behov känns de behagliga. Det som kanske inte alltid är acceptabelt i en social situation är tvärtom extra välkommet nu under övningen. Men försök för den skull inte att framkalla dem med avsikt. Det räcker med att släppa fram den när de kommer av sig själva.</i></p>
<p><i>"Frihet" är alltså det första nyckelordet för denna övning. Att ge andningen fullständig frihet är det bästa sättet att samarbeta med den. Varje avsiktlig påverkan kommer bara att störa det subtila samspelet med den reflexstyrda regleringen.</i></p>
<p><i>Om vi lugnt iakttar andningen kan vi också konstatera att vi stör den både mycket och ofta. Mellan vårt medvetande som i bästa välvilja utför övningen och det djupt liggande samspelet från reflexer i vårt omedvetna kan vi urskilja ett mellanled av undermedvetna reaktioner. Det är detta nätverk av förvärvade vanor som stör den djupaste, medfödda regleringsförmågan. Dessa vanor kan inte förstöra mekanismen fullständigt, vilket skulle bli vår död, utan bara hämma den. Men det är tillräckligt för att ge oss obehag.</i></p>
<p><i>Att känna igen dessa störningar redan från första början, just när de visar sig, och utan ansträngning så mycket som möjligt låta andningen återfå sin frihet, det är den första aspekten av denna övning. Det innebär att vi återlämnar till kretsloppet av reflexer uppgiften att sköta andningen åt oss, vilket det klarar alldeles utmärkt på egen hand. Det handlar alltså inte om att anstränga sig, utan tvärtom att låta bli all onödig ansträngning.</i></p>
<h3>Mental närvaro</h3>
<p>Ordet frihet sammanfattar i allt väsentligt den fysiologiska aspekten av övningen. Nästa nyckelord berör den psykologiska aspekten: "närvaro" , mental närvaro. Samtidigt som vi på det kroppsliga planet ger andningen maximal frihet skall vi försöka att på det psykologiska planet behålla kontakten med den.</p>
<p>Denna kontakt kan det omedvetna inte ta ansvar för, som det gör med andningen. Det är i stället den "mentala närvaron" som gör denna subtila ansträngning möjlig. Ordet ansträngning är egentligen alltför otympligt att användas om denna lätta, naturliga aktivitet.</p>
<p>Att ta kontakt med bukens rörelser i andningen är lätt. Men det är lika lätt att förlora kontakten, den tycks vara lika snabbt funnen som försvunnen. Mycket snart börjar vi tänka på annat, vi blir distraherade och glömmer andningen. Efter en stund kommer vi plötsligt ihåg övningen och tar på nytt kontakt med den för att snart förlora den igen.</p>
<p>Bli inte förvånad över att uppmärksamheten kommer och går på detta sätt, det är i själva verket oundvikligt till en början. Bara den som aldrig på allvar har försökt att hålla kvar den mentala närvaron i oavbruten kontakt med någonting kan förvåna sig över det.</p>
<p>Om andningsmekanismen nu ter sig gammal, pålitlig, förtroendeingivande och i stånd att fungera felfritt hela livet igenom, så är den mentala närvaron en ny möjlighet i oss. Den utvecklas vid treårsåldern och ger oss då för första gången möjlighet att uppleva "jag är jag"! Den förstärks under ungdomsåren och går igenom en viktig stabiliseringsfas i tjugoårsåldern. Men den är hela tiden bräcklig och ostadig, som ett blinkande ljus.</p>
<p>Ibland finns den mentala närvaron där och låter oss möta den yttre omständigheterna  ansikte mot ansikte och i största mentala  klarhet fatta välunderbyggda och kreativa beslut och ta ansvar för våra handlingar och konsekvenserna av dem.</p>
<p>Men ofta, i själva verket allra oftast, finns den mentala närvaron inte där eller är nedbländad som en svag nattbelysning. Vi är tankspridda, överhopade av mentala och emotionella associationer utan något samband med nuet. Vi reagerar på det som händer i den aktuella situationen med automatismer som härrör från vårt förflutna, med vanor som vi knappt är medvetna om och som aldrig anpassar sig helt till det närvarande.</p> 
<p>Andningsreflexerna har vi fått gratis, men vår förmåga till mental närvaro behöver växa till sig. Den visar sig mer som en möjlighet än som en realitet. Att gradvis låta närvaron växa till, det är den psykologiska aspekten av övningen.</p>
<p>Det räcker med att återvända till kontakten med andningen via händerna på magen varje gång man vaknar upp ur sin distraktion. Övningen består just av denna rörelse fram och tillbaka. Det är i det naturliga och avspända försöket att om och om igen återta kontakten som en större stabilitet och kraft i den mentala närvaron växer fram.</p>
<p>Övingen bär frukt bara om den utförs lätt och utan tvång.</p>
<p>Försök inte att hålla kvar kontakten krampaktigt. En överdriven ansträngning leder bara till att du förlorar andningens frihet. Varje spänning, varje hämning av andningen är en larmsignal som berättar att du är knuten någonstans.</p>
<p>Den riktiga mentala närvaron kan liknas vid månljuset som speglas på en flod och utan någon tyngd vilar på vattenytan. Månljuset ligger tätt på varje våg utan att flytta på sig. Det lyser på det strömmande vattnet men hindrar inte dess flöde.</p>
<h3>Balans</h3>
<p>Övningens hjärtpunkt ligger i balansen mellan den fria andningen och den ogrumlade mentala närvaron. Där förenas de båda polerna i människans väsen.</p>
<p>Det omedvetnas pol förkroppsligas i ämnesomsättningsfunktionerna som har sitt centrum i buken. Det styrs av det vegetativa nervsystemet och de centra av hjärnan som ligger längst ner och närmast ryggmärgen.</p>
<p>Medvetandets pol representeras av perceptionens, tankens och jagmedvetandets klara funktioner. Denna pol har sitt centrum i huvudet och styrs av hjärnbarken, som är hjärnans yngsta del såväl i det enskilda embryots utvedcklig som i utvecklingen av hela människoarten.</p>
<p>Mellan dessa båda poler bildar andningen en rytmisk gräns, precis som dess viktigaste muskel, diafragman, delar bålen i två halvor. Andningen har en unik dubbelställning: den tillhör kroppens automatiska funktioner men kan samtidigt klart förnimmas av medvetandet, liksom vågen på  havets yta är en av oceanen men samtidigt förenar himmel och hav genom sin rytmiska rörelse.</p>
<p>Om vi fullföljer övningen utan att ha för avsikt att lyckas till varje pris, om vi bara lugnt fortsätter våra försök, kommer detta att inleda en process. Genom hela serien av försök och misslyckanden kommer den att bära frukt alldeles av sig själv när tiden är mogen.</p>
<h4>Kom bara ihåg: att öva är att försöka, inte att lyckas.</h4>
<h3>Övningens frukter</h3>
<p>Vissa resultat börjar märkas redan efter de allra första försöken, andra först efter upprepade övningar.</p>
<p>Vi går alla in i en övning som denna från olika utgångspunkter eftersom vi från födelsen bär på olika genetiskt bagage.</p>
<p>Mot denna personliga bakgrund sätter sedan vår egen historia, vårt livs materiella, sociala, känslomässiga och intellektuella förhållanden sina spår. Vanor bildas och många av dem sjunker ner i det omedvetna och påverkar oss utan att vi märker det. Två vuxna personer kan alltså inte starta utifrån en och samma utgångspunkt.</p>
<p>Den övning som föreslås här kan utföras på samma sätt av alla, eftersom den bygger på gemensamma element: andningsreflexer och mental närvaro. Men i vilken ordning resultaten följer, vilken betydelse de får och hur långvariga de blir kommer med nödvändighet att variera från person till person, beroende på hur vars och ens förvärvade vanor fungerar. Detta påpekande gäller för alla övningar som jag kommer att beskriva.</p>
<p>Jag vill ändå försöka ge några anvisningar. De första resultaten av övningarna kommer i synnerhet att beröra medvetandegörandet. Vissa fakta kommer att framstå klarare. Vårt intresse, som hittills framför allt har varit riktat mot yttervärlden, kommer att stimuleras av en mängd nya faktorer i förnimmelserna från den egna kroppen.</p>
<h3>Enhet</h3>
<p>Låt oss gå tillbaka til de första försöken: vi behåller kontakten med andningen just så som den visar sig fritt i solarplexusområdet under våra händer. Vi accepterar andningen sådan den är och ger den tid att vänja sig vid vår uppmärksamhet. Vi kommer att märka att den blir allt mera regelbunden efter hand, att bukens rörelser mer och mer börjar likna en våg som stiger och sjunker under våra fingrar och som av sig själv, liksom trevande, söker sin egen optimala rytm och plats.</p>
<p>Därpå konstaterar vi att rörelsen inte begränsas bara till det område där våra fingrar har uppmärksam kontakt. Efterhand kan vi känna att rörelsen blir regelbunden och allt tydligare hur den långsamt breder ut sig i hela buken och i hela bröstkorgen. Det ställe där våra fingrar vilar upplevs mer och mer som en passage, som en svängdörr mellan buken och bröstkorgen. Genom denna öppna dörr förenas den övre och den nedre delen av kroppen i rytmisk kontaḱt.</p>





<p>Hi there! I'm the proud creator of this site, which I built with Gatsby.</p>
    </Layout>
  )
}
export default AboutPage
