import * as React from 'react'
import Layout from '../components/layout'
const AboutPage = () => {
  return (
    <Layout pageTitle="Den harmoniska kroppen">

<h3>Att sitta</h3>
<p>Barnet är visserligen redo att andas i samma ögonblick som det föds, men det kan varken stå eller gå. Medan den lilla kycklingen springer omkring från sin första levnadsdag krävs det mer än ett år innan människobarnet uppnår samma färdighet.</p>
<p>För att detta skall lyckas krävs att nervsystemet utvecklas. Ett skyddande fettämne, myelinet, måste undan för undan bildas runt nerverna för att möjliggöra överföringen av de impulder som skall sörja för kontrollen av muskelsystemet. Denna myeliniseringsprocess går i riktning från huvudet ner mot halsen för att så småningom nå ut till hela kroppen.</p>
<p>Efter några veckor lyder halsen de viljestyrda impulserna och det lilla barnet kan hålla huvudet upprätt. Och så kommer den dag då ryggen erövrats och barnet för första gången kan sitta själv, på sin egen bak, tack vare att det etablerat detta för människan unika samspel med tyngdkraften som leder till den upprätta kroppställningen.</p>
<p>Det rör sig inte här om en medfödd förmåga utan om något nytt som förvärvats. Denna koordination med anti-tyngdkraften är en inlärning med mycket gamla rötter. Den ombesörjs till stor del av den djupast liggande ryggmusklaturen, närmast ryggraden med sina korta fibrer. Den är konstruerad för ett stabilt, kontinuerligt och i det närmast outtröttligt arbete tack vare ett kontaktsystem mellan fibrerna. Bland dessa muskler är den längsgående ryggmuskeln (m erector spinae) den viktigaste. Den omsluter hela ryggraden, från den andra halskotan ända ner till korsbenet i förbindelse med bäckenet.</p>
<p>När denna koordination är etablerad fungerar den som en samlad reflektorisk aktivitet som utlöses av tyngdkraften. Den styrs av omedvetna centra i lillhjärnan och storhjärnans bas. Tack vare denna koordination kan en frisk människa utan medveten viljeansträngning bibehålla sin lodräta kroppsställning när han sitter genom att utnyttja de hållningsreflexer eller posturala reflexer som grundlagts under de första levnadsmånaderna. Reflexerna har till uppgift att ge oss ett stabilt stöd under hela vår vakna aktivitet.</p>
<p>Vi bör klart skilja mellan å ena sidan denna reflexmässiga aktivitet som gör den lodräta hållningens muskulära grundspänning mot tyngdkraften möjlig och å andra sidan den muskelaktivitet, som gör att vi kan sätta oss, böja oss eller resa oss upp.</p>
<p>Reflexaktiviteten i ryggens djupt liggande muskler gör det möjligt för koordinationen av våra viljestyrda muskler att undan för undan förfinas. Man använder bålens ytligare liggande, långfibriga muskler, uppbyggda för ett intensivt men kortvarigt arbete. Dessa muskler styrs huvudsakligen från vårt motoriska centrum i storhjärnans bark.</p>
<p>När man väl erövrat den lodräta balansen har man inte längre något behov av ryggen eller bukens ytligt liggande muskler för det statiska arbetet. Dessa muskler kan då disponeras dels för att möjliggöra den fria andningskoordinationen, dels för att engageras helt och hållet i eventuella viljestyrda rörelser.</p>
<p>Den nödvändiga förutsättningen för att hållningsreflexerna i ryggen skall interagera normalt är ett riktigt förhållande till tyngdkraften, eller med andra ord: den riktiga lodlinjen i bålens hela massa.</p>
<p>I och med att man har funnit den vertikala balansen framkallar tyngdkraftens ständiga dragning nedåt reflexmässigt den rätta muskelspänningen. Resultatet blir att tyngdkraften subjektivt tycks förlora sin verkan. Eftersom den motbalanseras exakt av hållningsreflexerna märker man den inte. Man känner sig fysiskt lätt och fri och psykiskt i god form. Kroppen har inte längre någon tyngd.</p>
<h3>Den centrala övningen</h3>
<p>I de liggande övningarna i föegående kapitel upplevde vi det horisontala läget, det stöd som underlaget ger oss alltifrån födseln, och samtidigt också andningens frihet. Längre fram kommer vi att återfinna samma element i den sittande ställningen då vi medvetet upplever det stadium som vi passerade under livets första månader; att resa upp bålen vertikalt i balans på bäckenet.</p>
<h3>Balans</h3>
<p>För denna övning behöver vi en stol eller en pall av normal höjd med horisontal sits. Det går inte bra med en fåtölj eller en soffa eller en sängkant och inte heller med en stol med alltför låg höjd, i alla fall inte till en början.</p>
<p><i>Sätt dig på främre delen av stolsitsen, utan något stöd för ryggen, så att sätet, men inte låren, får stöd mot underlaget.</i></p>
<p><i>Lossa på krage och skärp om det behövs, så att inga kläder sitter åt eller trycker mot halsen, bröstet eller magen. Många moderna, åtsittande byxor är bekväma när man står, men har en tendens att strama när man sitter. I så fall kan det bli nödvändigt att knäppa upp i midjan för att släppa magen fri.</i></p>
<p><i>Släpp isär knäna så att det bildas en vinkel mellan låren som kan variera melln 30 och 90 grader. När du kan behålla låren i detta läge utan ansträngning är den individuella vinkeln den rätta. I denna vinkel kan också låren och bäckenet spänna av.</i></p>
<p><i>Placera båda fotsulorna mot golvet, ungefär rakt under knäna. Vinkeln mellan fötterna skall motsvara vinkeln mellan låren. Justera ställningen till dess benen vilar stadigt och bekvämt.</i></p>
<p><i>I denna ställning är det önskvärt att knäna befinner sig något lägre än bäckenet.Det ger en bättre upprätningsreflex nedifrån och upp genom ryggen.</i></p>
<p><i>Om dina ben är mycket långa så att knäna kommer högre upp än bäckenet kan det vara nödvändigt att höja stolssitsen med en kudde eller en bok. En pianopall med reglerbar höjd kan också fungera bra.</i></p>
<p><i>För samman händerna på ett sätt som känns naturligt för dig och låt handlederna stödja på låren ganska nära bålen, så att armarna vilar avspända utan att dra dig framåt.</i></p>
<p><i>Du är nu redo att leka med tyngdkraften för att finna den optimala balansen för din kropp i dess nuvarande tillstånd.</i></p>
<p><i>Gör dig först medveten om din bål som en helhet, från bäckenets botten ända till hjässan. Sträck så på bålen, långsamt och utan ansträngning, som för att röra vid taket med hjässan. Spänn sedan av genom att låta bålen, utan ansträngning känna stödet från stolssitsen, som en pelare i balans,sten mot sten: bäcken, bröst och huvud i jämvikt utan någon spänning.</i></p>
<p><i>Upprepa denna sträckning av bålen två gånger och låt den varje gång följas av en vila i balans utan ansträngning. Med hela bålen på detta sätt avspänd och med buken, bröstkorgen och huvudet förenade till en helhet pendlar du nu ett tiotal gånger med små rörelser från sida till sida, till dess du hittar den lodlinje som du tycker ger dig det bästa balansläget mellan de båda sidorna.</i></p>
<p><i>Pendla sedan ett tiotal gånger med små rörelser framåt och bakåt. Försök också här att avsluta i den lodlinje där framåt och bakåt neutraliseras i en naturlig och stabil balans.</i></p>
<p>Om du nu har hittat den riktiga lodlinjen sitter du bekvämt, väl förankrad i stolssitsen, utan att känna någon spänning. Hållningsreflexerna stöder dig osynligt, medan den ytliga muskulaturen är i vila.</p>
<p>Särskilt halsen är avspänd. De hållningsreflexer som bär upp huvudet sträcker sig igenom hals och nacke som en förlängning av det stora flöde som stiger upp från bäckenet. Den viljemässiga kontrollen av muskulaturen genom nervsystemet utgår från huvudet, medan den reflexmässiga startar nedifrån kroppens underlag i en mäktig koordination som förfinas ju högre den når, precis som ryggradens kotor blir allt mindre ju närmare huvudet de är belägna. Längst upp bärs huvudet upp av halsen som blomman på sin stjälk, livnärd av en ström av sav som stiger upp från jorden.</p>
<h3>Former och processer</h3>
<p>Lägg märke till att även om det muskulära stödet hör samman med ryggraden skall kroppens mittaxel, kring vilken kroppen finner sin balans och kring vilken kontakten med tyngdkraften utspelas, inte förväxlas med ryggraden. Mittaxeln går lodrätt mitt igenom bålen och utmynnar i bäckenet i sittbenen, de skelettutskott som vi sitter på.</p>
<p>Mittaxeln kan liknas vid en osynlig lodlina som går genom hela buken, bröstkorgen och huvudet. Om dessa tre plan inte befinner sig i en riktig balans i förhållande till varandra blir bålen ett slags lutande tornet i Pisa och man måste spänna sig för att inte sjunka ihop. Då tvingas den ytligt liggande muskulaturen, som är avsedd för ett intensivt men kortvarigt arbete, att vara i funktion permanent på samma sätt som hållningsreflexerna, och det är härifrån som de kompensatoriska spänningarna i buken, ryggen, halsen och axlarna kommer. Med tiden utvecklas spänningarna till muskelkramper, smärtor och blockeringar. Leder som ständigt befinner sig i felaktiga lägen kan också gradvis utveckla sjukdomar som artrit och artros.</p> 
<p>För sådana kompensationsskador finns det inget annat varaktigt botemedel än att på nytt söka sig fram till en riktigare balans. När balansen gjort de kompensatoriska spänningarna överflödiga kan de avta eller åtminstone upphöra att öka. Balansen gör också att lederna kan återgå till sina funktionella lägen.</p>
<p>Sökandet efter balansen kommer att förfinas med tiden. de första försöken kan bara bli trevande, men det räcker med att varje gång, så gott man kan, försöka hitta den för ögonblicket bästa balansen. Redan detta kommer att lösa upp vissa spänningar, förbättra förnimmelsen av den egna kroppen och leda till ett bättre sätt att vara, som visserligen alltjämnt är relativt men redan fullt märkbart. Dessa första resultat jämnar vägen för de framsteg som följer sedan.</p>
<p>Musklernas vanemässiga sätt att arbeta måste undan för undan förändras så att de nuvarande kompensationerna kan ersättas med en funktionell enhetlighet som är äldre och ligger djupare i vävnaderna. Utom vid vissa undantagsfall (förlamning till exempel) finns det ursprungliga funktionella systemet alltid där, berett att fungera men dolt och insnört av spänningar som vi lagt oss till med senare. Det ursprungliga systemet etablerades under våra första levnadsmånader medan kompensationerna  är ytligare och yngre. Men vi kan inte bli av med dem utan att på nytt ingå en förening med de äldre reflexerna, som är vårt verkliga stöd.</p>
<p>Det sökande efter balans som jag föreslår här är en process som verkar på längre sikt genom att man regelbundet repeterar övningen. Hållningsreflexerna som helhet utgör också en process, som upprättar vissa förbindelser mellan bålens delar. Erfarenheten har visat att det på sikt är mycket effektivt att närma sig dem som en helhet som påverkar hela bålen.</p>
<p>Jag gjorde själv i början misstaget att negligera helhetsprocessen till förmån för den enskilda formen. Jag försökte lösa mina svårigheter genom att utifrån imitera det som jag tyckte var den rätta formen, jag härmade lärare eller andra beundrade förebilder. Alla dessa försök blev fiaskon, och hur många sådana fiaskon har jag inte sedan sett omkring mig!</p>
<p>Dessa felaktiga försök går bara att genomföra om man tar hjälp av det ytligare, viljestyrda muskelsystemet som egentligen inte har detta till uppgift. När allt kommer omkring lägger de bara ytterligare kompensationer till dem som redan finns.</p>
<p>Det är alltså med avsikt som jag inte beskriver ryggens, halsens eller bäckenets "rätta form" i den sittande övningen. Formen varierar från person till person och allt efter övningens förlopp. I varje ögonblick ger formen uttryck åt vårt aktuella tillstånd, fysiskt och psykiskt, men också åt hela vårt förflutna med de ärr det lämnat i vår kropp. Men formen ger också uttryck åt de underliggande, sunda processerna. Det är dessa som ger något universellt och allmängiltigt åt friska små barns rörelser och hållning.</p>
<p>Ryggraden bildar en integrerad helhet i vilken krökningarna i ländryggen, bröstryggen och halsryggen balanseras och kompenserar varandra.</p>
<p>Jag erbjuder övningar där dessa kompensationer reduceras undan för undan genom att de balanseras mot varandra i en enda orgaisk helhet.</p>
<p>Det muskulära systemet kan behålla sin styrka bara genom att arbeta. Men för att arbeta måste det ha ett motstånd. Liksom hantlar erbjuder ett motstånd så att armmusklerna kan stärkas, bjuder kroppens egen vikt genom tyngdkraften det motstånd som hållningsreflexerna behöver för att bli starkare.</p>
<p>Om vi alltså placerar bålen i en lodrät balans utan ryggstöd skapar vi på så sätt automatiskt de förutsättningar som tvingar hållningsreflexerna att arbeta och stärkas.</p>
<p>Av iakttagelser och praktisk erfarenhet har jag förstått vilken exceptionell visdom som reglerar dessa djupa processer och deras anpassning till de hinder som vi omedvetet sätter upp för dem. Inom vissa gränser naturligtvis, som dock är mycket vidare än vi föreställer oss, är du alltid i verksamhet för att dra största möjliga fördel av de usla villkor som vi påtvingar dem.</p>
<p>Om vi tar hjälp av den visdom som ligger i reflexerna, om vi under övningens lopp mer och mer utgår från dessa processer, kommer de att fördjupa sin verkan. Vi kan då få se hur samma, levande och fria former växer fram inifrån, former som liknar de storslagna exempel vi kan finna i antikens eller renässansens bildhuggarkonst.</p>
<h3>Frihet</h3>
<p>I vår kropp, sådan den är just nu, har vi alltså funnit tre nivåer som fungerar samstämmigt:</p>
<p>1. vår medvetna intension att fungera på bästa sätt;</p>
<p>2. mycket gamla och djupt liggande reflexer som till exempel hållningsreflexerna, som verkar från djupet av vårt kroppliga omedvetna för att ge oss ett sunt och effektivt stöd;</p>
<p>3. ett skikt av deformeringar och kompensationer som vi lagt oss till med under loppet av vår psykologiska och kroppsliga utveckling. Denna nivå framträder som ett mellanplan mellan de medvetna intentionerna och de djupare och mer omedvetna skikten, som trots allt ansvarar för vår överlevnad och vår fysiska integritet så långt omständigheterna tillåter.</p>
<p>Den första etappen i den sittande övningen gick ut på att återfinna bålens optimala lodräta
balans inom våra aktuella gränser. Vi har nått dithän genom att medvetet förnya kontakten med de ursprungliga hållningsreflexerna och genom att undan för undan koppla av de perifera spänningarna, som är vanemässiga uttryck för våra omedvetna svårigheter.</p>
<p>När vi går över från den horisontella kroppsövningen till den sittande, vertikala, kan man dessutom via ledförbindelserna mellan ryggrad och bröstkorg klart se samspelet mellan kroppshållning och andning.</p>
<p>En bröstkorg som genom felaktiga andningsvaror blivit alltför öppen eller alltför hopklämd påverkar bröstkotorna och indirekt också den övriga ryggraden. Denna fungerar som en integrerad helhet och kompenserar oundvikligen varje lokal deformering på någon annan nivå.</p> 
<p>Om nu sökandet efter den optimala balansen gjort det möjligt för oss att åter utgå från hållningsreflexerna så kan de emellertid inte spela sin roll helt och fullt förrän de deformeringar som beror på den felaktiga andningskoordinationen gradvis avtagit.</p>
<p>Redan i den liggande övningen har vi kunnat gå in i den process som frigörandet av andningen innebär. När andningen återfått största möjliga frihet kan den ge en inre massage som spänner av, ger tonus och balans åt den muskulära koordinationen som omsluter hela bålen från bäckenbotten ända till halsen.</p>
<p>När vi nu sitter i den lodräta ställningen kommer andningens muskelkoordination att samarbeta med hållningsreflexerna och undan för undan skulptera om kroppen. Dessa båda stora kretslopp av reflexer fungerar som en osynlig skulptör, som genom att aktivera de försvagade funktionerna och frigöra de ytliga spänningarna låter de ursprungliga, underliggande formerna träda fram på nytt.</p>
<p>Vi märker då att hållningsreflexerna och andningsreflexerna understöder varandra. Om man hittar den riktiga lodlinjen när man spänner av de perifera spänningarna öppnar detta kroppen och ställer den till förfogande för andningens flöde.</p>
<p>Dessutom strävar den allt friare andningen efter att återföra bålens hållning fill den riktiga lodlinjen, vilket i sin tur underlättar för andningsflödet att passera genom halsen, bröstet och buken.</p>
<p>När vi har hittat balansen kan vi med förtroende vila i de anti-tyngdreflexer som håller kroppen upprätt och vända uppmärksamheten mot andningen. Om vi har ägnat oss åt den liggande övningen en tid har vi redan känt den inre smaken av en friare andning. Det är denna som vi nu skall försöka återfinna i den lodräta ställningen.</p> 
<p><i>Nu skall vi inte hålla händerna mitt på kroppen utan i stället låta dem vila tillsammans på övre delen av låren.</i></p>
<p><i>Håll munnen stängd och andas bara genom näsan</i></p>
<p><i>Om man är förkyld eller kroniskt täppt i näsan bör snyta sig ordentligt för att göra den riktigt ren och därefter sluta munnen. Ta några djupa andetag, varannan gång genom vänster näsborre och varannan genom höger genom att hålla för den andra näsborren. Detta aktiverar blodcirkulationen och stimulerar nervändarna i näsans inre. Dessa senare påverkan genom reflexer diafragmans verksamhet. Håll hela tiden munnen sluten. Den luft som i den fria andningen som dras in genom diafragmans aktivitet räcker för att hålla näsan fri. Undan för undan kommer nästäppan att försvinna.</i></p>
<p><i>Vi lämnar andningen fullständigt fri att själv hitta sin plats. Vi  ger den tid att installera sig i vår lodräta kropp och ta den i besittning på sitt eget sätt</i></p>
<p>Acceptera att andningen kan göra avbrott och ta olika omvägar till dess att en viss regelbundenhet och stabilitet inträder av sig själv och som underlättas genom att kroppen är orörlig och i avspänd balans.</p>
<p>Alla mina kommentarer och alla de iakttagelser som du själv kunnat göra under den liggande övningen gäller också här.</p>
<h3>Mental närvaro</h3>
<p>De två första elementen i den sittande övningen var: balans för bålens fysiska massa utan någon ansträngning tack vare hållningreflexerna och frihet för aandningen och med den för alla de omedvetna fysilogiska processerna, för vilka den på sätt och vis är en budbärare.</p>
<p>Till detta kommer nu ett tredje element. Efter den fysiska aspekten med balansen som nyckelord och den fysiologiska med friheten som nyckelord kommer vi nu till den psykologiska, vars kännetecken är den mentala närvaron.</p>
<p>När balansen är stabil och andningen har funnit sin egen regelbundna rytm, fungerar dessa båda på egen hand genom reflexernas spel. Focus för övningen kan då i stället flyttas över till den mentala inställningen</p>
<p>Man kan likna den mentala närvaron vid en brinnande lampa och uppmärksamheten vid det ljussken den kastar. För att förstärka och stabilisera detta ĺjus riktar vi det mot ett bestämt mål och etablerar en medveten kontakt med detta. Det är denna kontakt som vi försöker behålla och medvetet återvänder till när vi har förlorat den.</p>
<p>Lägg märke till att när jag talar om uppmärksamhetens ljus så är det inte enbart en liknelse. Det kan hända, och det händer ofta, att vi med öppna ögon står rakt framför ett föremål eller en person men inte ser dem därför att vi har tankarna på annat håll. Och eftersom vi inte ser dem kommer vi inte heller ihåg dem. Det yttre ljuset är alltså inte tillräckligt för att vi skall se.</p>
<p>För att den fysiska perceptionen skall omvandlas till en medveten varseblivning krävs också detta uppmärksamhetens ljus, som vi liksom inifrån kastar på objekten, och inte bara på de yttre objekten utan också på de inre, dvs våra föreställningar, känslor och minnen.</p>
<p>Denna iakttagelse kan leda oss ytterligare ett steg. För detta ljus, som uppstått ur vår mentala närvaro, framträder den inre och den yttre världen som två beståndsdelar i ett enhetligt uppmärksamhetsfält. Att iaktta ett inre minne och därefter ett yttre föreemål är inte mycket annorlunda för detta ljus än att iaktta ett föremål på himlen efter att ha iakttagit ett föremål på marken. I båda fallen handlar det bara om att ändra den kontaktpunkt på vilken uppmärksamheten fäster sin ljusstråle.</p>
<p>Den mentala närvaron visar sig alltså vara en företeelse som radikalt skiljer sig från alla övriga i vårt psykologiska liv. Alla tankar, alla känslor, alla förnimmelser som vi är medvetna om kan bli objekt på vilka ljuset från den mentala närvaron projiceras. Det är endast denna närvaro som inom oss kan göra anspråk på benämningen subjekt.</p>
<p>Vi är ofta ovetande om detta elementära faktum, Det beror på att denna unika och centrala funktion, detta subjekt som är närvarande inom oss, mer eller mindre fefinner sig i dvala. Sovande försöker det, liksom i en dagdröm, identifiera sig med förnimmelser, idéer och känslor. Medvetenheten om detta subjekt kan på så sätt uttryckas som "jag är ledsen" eller "jag känner mig i form".</p>
<p>Men ibland händer det, under påverkan av en yttre intensiv eller oväntad situation, att denna sjlvständiga mentala närvaro, denna inre förnimmelse av "jag är" framträder tydligt. Då sker ett slag frigörelse, alldeles oberoende av hur intensiv vår känsla, vår glädje eller vår sorg är för stunden.</p> 
<p>I detta ögonblick vet man med bländande visshet: "jag är inte mina känslor. men jag är och har känslor".</p>
<p>Sådana intensiva upplevelser varar i allmänhet inte länge. Det förefaller som om praktiskt taget alla människor kan erinra sig ett eller ett par liknande ögonblick. I de flesta fall fäster vi ingen särskild uppmärksamhet vid dem och de faller i glömska. Men det är dessa ögonblick som kan tjäna som referensram och vara vägledande i en metod som den jag föreslår.</p>
<p>Detta centrala medvetande, denna förnimmelse av "jag är", visar sig alltså i den inre erfarenheten som en bakgrund mot vilken våra tankar, känslor och handlingar framträder, som när en klar himel skuggas av moln av alla de slag: lätta och tunga, moln som färgats rosa av våra glädjeämnen eller svarta av våra sorger. Liknelsen kan också bekräftas på ett annat område, nämligen i kontrasten mellan våra tankar, känslor och sinnesintryck som hela tiden är stadda i rörelse, förändras och utvecklas, och den alltid identiska men mer eller mindre intensiva förnimmelsen av detta "jag är", varje gång den blir medveten.</p>
<p>Existensen av denna mentala närvaro, detta centrala "jag är" som både medveten och personlig erfarenhet är något som radikalt skiljer den mänskliga arten från alla djurarter. Här föreligger ett kvalitativt språng i utvecklingen, analogt med det som skiljer växtriket från djurriket.</p>
<h3>Att sitta uppmärksamt</h3>
<p><i>Vi återvänder nu till vår övning</i></p>
<p><i>Denna gång ska vi ta blicken till hjälp: utan att sluta ögonen helt sänker du blicken mjukt ner mot golvet. Vid en vinkel av ungefär 45 grader från horisontlinjen kommer du att hitta ett viloläge där ögonen kan förbli halvslutna utan att fixera något föremål, men utan att stänga ute det yttre ljuset. Medan den liggande övningeen utfördes med slutna ögon skall vi hädanefter söka nå en tonisk balans mellan den djupa avspänningen och den spänning som råder i ett mera aktiverat tillstånd. Ögonens läge med halvt sluten blick svarar mot en sådan balans och har också en reflektorskt avspännande verkan på halsen.</i></p>
<p><i>Om man har en kraftig nervspänning i och kring ögonen med värk efter att ha läst, skrivit eller tittat mycket kan man gärna sluta ögonen i början av övningen, till dess de blivit så avspända att man kan återvända till balansen med halvslutna ögon.</i></p>
<p><i>Precis som i den liggande ställningen stabiliserar och utveclar man konkret sin mentala närvaro genom att ta kontakt med andningen. Sitt lodrätt med fri andning och känn lugnt efter hur du skall ta kontakt med andningen på ett nturligt sätt. Händerna skall inte längre vila på magen utan det är inifrån som du skall förnimma andningen.</i></p>
<p>Det rör sig om samma sökande som när en ryttare sitter upp p en häst utan sadel för att känna efter var och hur han skall sätta sig för att så naturligt som möjligt anpassa sig till sitt riddjur. Sitter han alltför nära halsen eller alltförnära bakdelen irriterar han hästen och sitter själv inte bra. När han hittar den rätta platsen blir resultatet en lättnad både för hästen och ryttaren.</p>
<p>När denna kontakt så småningom etablerats och vanan undan för undan gör det hela enklare, består hela övningen i att återvända hit varje gång vi blivit distraherade och fjärmat oss därifrån. Om den subtila och lätta övning upprepas lungt, stärker den precis som i den första övningen på golvet undan för undan vår mentala närvaro på samma sätt som när vi genom att böja armen stärker bicepsmuskeln. Detta är övningens hjärtpunkt.</p>
<h3>Övningens frukter</h3>
<h4><b>Balanskonstnären</b></h4>
<p>I förra kapitlet beskrev jag vilka verkningar andningsövningen kunde ha på vår organism. Samma effekter återfinns också och fördjupas i den sittande övningen. Den stor skillnaden består i att anti-tyngdreflexerna nu sätts i spel och gör det möjligt att behålla den upprätta vertikala hållningen.</p> 
  
  
  

 <p>Hi there! I'm the proud creator of this site, which I built with Gatsby.</p>
    </Layout>
  )
}
export default AboutPage
