import * as React from 'react'
import Layout from '../components/layout'
const AboutPage = () => {
  return (
    <Layout pageTitle="Den harmoniska kroppen">

<h3>Att sitta</h3>
<p>Barnet är visserligen redo att andas i samma ögonblick som det föds, men det kan varken stå eller gå. Medan den lilla kycklingen springer omkring från sin första levnadsdag krävs det mer än ett år innan människobarnet uppnår samma färdighet.</p>
<p>För att detta skall lyckas krävs att nervsystemet utvecklas. Ett skyddande fettämne, myelinet, måste undan för undan bildas runt nerverna för att möjliggöra överföringen av de impulder som skall sörja för kontrollen av muskelsystemet. Denna myeliniseringsprocess går i riktning från huvudet ner mot halsen för att så småningom nå ut till hela kroppen.</p>
<p>Efter några veckor lyder halsen de viljestyrda impulserna och det lilla barnet kan hålla huvudet upprätt. Och så kommer den dag då ryggen erövrats och barnet för första gången kan sitta själv, på sin egen bak, tack vare att det etablerat detta för människan unika samspel med tyngdkraften som leder till den upprätta kroppställningen.</p>
<p>Det rör sig inte här om en medfödd förmåga utan om något nytt som förvärvats. Denna koordination med anti-tyngdkraften är en inlärning med mycket gamla rötter. Den ombesörjs till stor del av den djupast liggande ryggmusklaturen, närmast ryggraden med sina korta fibrer. Den är konstruerad för ett stabilt, kontinuerligt och i det närmast outtröttligt arbete tack vare ett kontaktsystem mellan fibrerna. Bland dessa muskler är den längsgående ryggmuskeln (m erector spinae) den viktigaste. Den omsluter hela ryggraden, från den andra halskotan ända ner till korsbenet i förbindelse med bäckenet.</p>
<p>När denna koordination är etablerad fungerar den som en samlad reflektorisk aktivitet som utlöses av tyngdkraften. Den styrs av omedvetna centra i lillhjärnan och storhjärnans bas. Tack vare denna koordination kan en frisk människa utan medveten viljeansträngning bibehålla sin lodräta kroppsställning när han sitter genom att utnyttja de hållningsreflexer eller posturala reflexer som grundlagts under de första levnadsmånaderna. Reflexerna har till uppgift att ge oss ett stabilt stöd under hela vår vakna aktivitet.</p>
<p>Vi bör klart skilja mellan å ena sidan denna reflexmässiga aktivitet som gör den lodräta hållningens muskulära grundspänning mot tyngdkraften möjlig och å andra sidan den muskelaktivitet, som gör att vi kan sätta oss, böja oss eller resa oss upp.</p>
<p>Reflexaktiviteten i ryggens djupt liggande muskler gör det möjligt för koordinationen av våra viljestyrda muskler att undan för undan förfinas. Man använder bålens ytligare liggande, långfibriga muskler, uppbyggda för ett intensivt men kortvarigt arbete. Dessa muskler styrs huvudsakligen från vårt motoriska centrum i storhjärnans bark.</p>
<p>När man väl erövrat den lodräta balansen har man inte längre något behov av ryggen eller bukens ytligt liggande muskler för det statiska arbetet. Dessa muskler kan då disponeras dels för att möjliggöra den fria andningskoordinationen, dels för att engageras helt och hållet i eventuella viljestyrda rörelser.</p>
<p>Den nödvändiga förutsättningen för att hållningsreflexerna i ryggen skall interagera normalt är ett riktigt förhållande till tyngdkraften, eller med andra ord: den riktiga lodlinjen i bålens hela massa.</p>
<p>I och med att man har funnit den vertikala balansen framkallar tyngdkraftens ständiga dragning nedåt reflexmässigt den rätta muskelspänningen. Resultatet blir att tyngdkraften subjektivt tycks förlora sin verkan. Eftersom den motbalanseras exakt av hållningsreflexerna märker man den inte. Man känner sig fysiskt lätt och fri och psykiskt i god form. Kroppen har inte längre någon tyngd.</p>
<h3>Den centrala övningen</h3>
<p>I de liggande övningarna i föegående kapitel upplevde vi det horisontala läget, det stöd som underlaget ger oss alltifrån födseln, och samtidigt också andningens frihet. Längre fram kommer vi att återfinna samma element i den sittande ställningen då vi medvetet upplever det stadium som vi passerade under livets första månader; att resa upp bålen vertikalt i balans på bäckenet.</p>
<h3>Balans</h3>
<p>För denna övning behöver vi en stol eller en pall av normal höjd med horisontal sits. Det går inte bra med en fåtölj eller en soffa eller en sängkant och inte heller med en stol med alltför låg höjd, i alla fall inte till en början.</p>
<p><i>Sätt dig på främre delen av stolsitsen, utan något stöd för ryggen, så att sätet, men inte låren, får stöd mot underlaget.</i></p>
<p><i>Lossa på krage och skärp om det behövs, så att inga kläder sitter åt eller trycker mot halsen, bröstet eller magen. Många moderna, åtsittande byxor är bekväma när man står, men har en tendens att strama när man sitter. I så fall kan det bli nödvändigt att knäppa upp i midjan för att släppa magen fri.</i></p>
<p><i>Släpp isär knäna så att det bildas en vinkel mellan låren som kan variera melln 30 och 90 grader. När du kan behålla låren i detta läge utan ansträngning är den individuella vinkeln den rätta. I denna vinkel kan också låren och bäckenet spänna av.</i></p>
<p><i>Placera båda fotsulorna mot golvet, ungefär rakt under knäna. Vinkeln mellan fötterna skall motsvara vinkeln mellan låren. Justera ställningen till dess benen vilar stadigt och bekvämt.</i></p>
<p><i>I denna ställning är det önskvärt att knäna befinner sig något lägre än bäckenet.Det ger en bättre upprätningsreflex nedifrån och upp genom ryggen.</i></p>
<p><i>Om dina ben är mycket långa så att knäna kommer högre upp än bäckenet kan det vara nödvändigt att höja stolssitsen med en kudde eller en bok. En pianopall med reglerbar höjd kan också fungera bra.</i></p>
<p><i>För samman händerna på ett sätt som känns naturligt för dig och låt handlederna stödja på låren ganska nära bålen, så att armarna vilar avspända utan att dra dig framåt.</i></p>
<p><i>Du är nu redo att leka med tyngdkraften för att finna den optimala balansen för din kropp i dess nuvarande tillstånd.</i></p>
<p><i>Gör dig först medveten om din bål som en helhet, från bäckenets botten ända till hjässan. Sträck så på bålen, långsamt och utan ansträngning, som för att röra vid taket med hjässan. Spänn sedan av genom att låta bålen, utan ansträngning känna stödet från stolssitsen, som en pelare i balans,sten mot sten: bäcken, bröst och huvud i jämvikt utan någon spänning.</i></p>
<p><i>Upprepa denna sträckning av bålen två gånger och låt den varje gång följas av en vila i balans utan ansträngning. Med hela bålen på detta sätt avspänd och med buken, bröstkorgen och huvudet förenade till en helhet pendlar du nu ett tiotal gånger med små rörelser från sida till sida, till dess du hittar den lodlinje som du tycker ger dig det bästa balansläget mellan de båda sidorna.</i></p>
<p><i>Pendla sedan ett tiotal gånger med små rörelser framåt och bakåt. Försök också här att avsluta i den lodlinje där framåt och bakåt neutraliseras i en naturlig och stabil balans.</i></p>
<p>Om du nu har hittat den riktiga lodlinjen sitter du bekvämt, väl förankrad i stolssitsen, utan att känna någon spänning. Hållningsreflexerna stöder dig osynligt, medan den ytliga muskulaturen är i vila.</p>
<p>Särskilt halsen är avspänd. De hållningsreflexer som bär upp huvudet sträcker sig igenom hals och nacke som en förlängning av det stora flöde som stiger upp från bäckenet. Den viljemässiga kontrollen av muskulaturen genom nervsystemet utgår från huvudet, medan den reflexmässiga startar nedifrån kroppens underlag i en mäktig koordination som förfinas ju högre den når, precis som ryggradens kotor blir allt mindre ju närmare huvudet de är belägna. Längst upp bärs huvudet upp av halsen som blomman på sin stjälk, livnärd av en ström av sav som stiger upp från jorden.</p>
<h3>Former och processer</h3>
<p>Lägg märke till att även om det muskulära stödet hör samman med ryggraden skall kroppens mittaxel, kring vilken kroppen finner sin balans och kring vilken kontakten med tyngdkraften utspelas, inte förväxlas med ryggraden. Mittaxeln går lodrätt mitt igenom bålen och utmynnar i bäckenet i sittbenen, de skelettutskott som vi sitter på.</p>
<p>Mittaxeln kan liknas vid en osynlig lodlina som går genom hela buken, bröstkorgen och huvudet. Om dessa tre plan inte befinner sig i en riktig balans i förhållande till varandra blir bålen ett slags lutande tornet i Pisa och man måste spänna sig för att inte sjunka ihop. Då tvingas den ytligt liggande muskulaturen, som är avsedd för ett intensivt men kortvarigt arbete, att vara i funktion permanent på samma sätt som hållningsreflexerna, och det är härifrån som de kompensatoriska spänningarna i buken, ryggen, halsen och axlarna kommer. Med tiden utvecklas spänningarna till muskelkramper, smärtor och blockeringar. Leder som ständigt befinner sig i felaktiga lägen kan också gradvis utveckla sjukdomar som artrit och artros.</p> 
<p>För sådana kompensationsskador finns det inget annat varaktigt botemedel än att på nytt söka sig fram till en riktigare balans. När balansen gjort de kompensatoriska spänningarna överflödiga kan de avta eller åtminstone upphöra att öka. Balansen gör också att lederna kan återgå till sina funktionella lägen.</p>
  

 <p>Hi there! I'm the proud creator of this site, which I built with Gatsby.</p>
    </Layout>
  )
}
export default AboutPage
